# Generated by Django 4.2.6 on 2023-10-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_lead_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='pg_rating',
            new_name='leadActor',
        ),
        migrations.AddField(
            model_name='movie',
            name='pgRating',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
    ]
